Q1. Consider the following sensor readings: temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40]) A sensor has an average measurement error of +2°C. Perform the following without using a for loop:
a. Add 2°C to every reading using vectorization.
b. Convert all temperatures from Celsius to Fahrenheit using: F=95C+32
c. Identify all readings greater than 32°C using Boolean indexing.
d. Count how many readings exceed 32°C.
e. Explain how vectorization and Boolean indexing can make data processing more efficient than explicitly iterating through every value.


In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
print("Original temperature readings:", temperature)

corrected = temperature + 2
print("a. After adding 2 C:", corrected)

fahrenheit = (9 / 5) * corrected + 32
print("b. Temperatures in Fahrenheit:", fahrenheit)

greater_than_32 = corrected[corrected > 32]
print("c. Readings greater than 32 C:", greater_than_32)

count_exceed = np.sum(corrected > 32)
print("d. Number of readings exceeding 32 C:", count_exceed)

print(
    "e. Vectorization applies the same operation to the whole array at once, "
    "so NumPy uses fast compiled code instead of a slow Python for-loop. "
    "Boolean indexing selects matching values with a single comparison mask, "
    "which is also done in compiled code. Both avoid iterating over each "
    "reading in Python and are therefore faster and more concise for large data."
)


Original temperature readings: [25 28 31 35 38 27 33 40]
a. After adding 2 C: [27 30 33 37 40 29 35 42]
b. Temperatures in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
c. Readings greater than 32 C: [33 37 40 35 42]
d. Number of readings exceeding 32 C: 5
e. Vectorization applies the same operation to the whole array at once, so NumPy uses fast compiled code instead of a slow Python for-loop. Boolean indexing selects matching values with a single comparison mask, which is also done in compiled code. Both avoid iterating over each reading in Python and are therefore faster and more concise for large data.


Q2. The following matrix represents the number of daily steps recorded by four users over three days: steps = np.array([ [5000, 6200, 7100], [8000, 7500, 9000], [4500, 5100, 4800], [9000, 8500, 9500]]) Perform the following:
a. Calculate the total steps recorded.
b. Calculate the mean number of steps.
c. Find the maximum and minimum values.
d. Calculate the total steps for each day using axis=0.
e. Calculate the total steps for each user using axis=1.
f. Find the user/day position containing the maximum number of steps using argmax().


In [2]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])
print("Steps matrix:")
print(steps)

print("a. Total steps recorded:", np.sum(steps))
print("b. Mean number of steps:", np.mean(steps))
print("c. Maximum:", np.max(steps), "Minimum:", np.min(steps))
print("d. Total steps for each day (axis=0):", np.sum(steps, axis=0))
print("e. Total steps for each user (axis=1):", np.sum(steps, axis=1))

flat_index = np.argmax(steps)
user, day = np.unravel_index(flat_index, steps.shape)
print("f. argmax() flat index:", flat_index)
print("   User index:", user, "(User", user + 1, ")")
print("   Day index:", day, "(Day", day + 1, ")")
print("   Maximum steps at this position:", steps[user, day])


Steps matrix:
[[5000 6200 7100]
 [8000 7500 9000]
 [4500 5100 4800]
 [9000 8500 9500]]
a. Total steps recorded: 84200
b. Mean number of steps: 7016.666666666667
c. Maximum: 9500 Minimum: 4500
d. Total steps for each day (axis=0): [26500 27300 30400]
e. Total steps for each user (axis=1): [18300 24500 14400 27000]
f. argmax() flat index: 11
   User index: 3 (User 4 )
   Day index: 2 (Day 3 )
   Maximum steps at this position: 9500


Q3. Write a Python program using NumPy to perform the following operations:
a. Create the following NumPy array: original = np.array([1, 2, 3, 4, 5, 6])
b. Create a slice containing elements from index 1 to 4 and store it in a variable named subset.
c. Modify the first element of subset to 999 and display both original and subset.
d. Create another slice from original, but this time use .copy(). Modify its first element to 500 and display original and the copied array.
e. Create a NumPy array containing the numbers from 1 to 12 using np.arange() and reshape it into a 3 × 4 matrix.
f. From the 3 × 4 matrix, extract the following using NumPy indexing and slicing:
• First row
• Last row
• Second column
• Elements from rows 1–2 and columns 2–3
g. Create a flattened version of the 3 × 4 matrix using both flatten() and ravel().
h. Modify an element in the array returned by ravel() and observe whether the original array is affected.
i. Modify an element in the array returned by flatten() and observe whether the original array is affected.
j. Display the shape, ndim, size, and dtype of the original 3 × 4 matrix.


In [3]:
original = np.array([1, 2, 3, 4, 5, 6])
print("a. original:", original)

subset = original[1:5]
print("b. subset (index 1 to 4):", subset)

subset[0] = 999
print("c. After modifying subset[0] = 999")
print("   original:", original)
print("   subset:", subset)
print("   Observation: original is also changed because a slice is a view.")

copied = original.copy()
copied[0] = 500
print("d. After modifying copied[0] = 500")
print("   original:", original)
print("   copied:", copied)
print("   Observation: original is unchanged because .copy() creates an independent array.")

matrix = np.arange(1, 13).reshape(3, 4)
print("e. 3 x 4 matrix:")
print(matrix)

print("f. First row:", matrix[0])
print("   Last row:", matrix[-1])
print("   Second column:", matrix[:, 1])
print("   Rows 1-2 and columns 2-3:")
print(matrix[0:2, 1:3])

flat_flatten = matrix.flatten()
flat_ravel = matrix.ravel()
print("g. flatten():", flat_flatten)
print("   ravel():", flat_ravel)

print("h. Modify ravel() result")
print("   matrix before:", matrix.tolist())
flat_ravel[0] = 100
print("   ravel() after change:", flat_ravel)
print("   matrix after ravel() change:")
print(matrix)
print("   Observation: original matrix is affected because ravel() returns a view when possible.")

print("i. Modify flatten() result")
flat_flatten[0] = 200
print("   flatten() after change:", flat_flatten)
print("   matrix after flatten() change:")
print(matrix)
print("   Observation: original matrix is not affected by changing flatten() because flatten() returns a copy.")

print("j. shape:", matrix.shape)
print("   ndim:", matrix.ndim)
print("   size:", matrix.size)
print("   dtype:", matrix.dtype)


a. original: [1 2 3 4 5 6]
b. subset (index 1 to 4): [2 3 4 5]
c. After modifying subset[0] = 999
   original: [  1 999   3   4   5   6]
   subset: [999   3   4   5]
   Observation: original is also changed because a slice is a view.
d. After modifying copied[0] = 500
   original: [  1 999   3   4   5   6]
   copied: [500 999   3   4   5   6]
   Observation: original is unchanged because .copy() creates an independent array.
e. 3 x 4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
f. First row: [1 2 3 4]
   Last row: [ 9 10 11 12]
   Second column: [ 2  6 10]
   Rows 1-2 and columns 2-3:
[[2 3]
 [6 7]]
g. flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
   ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
h. Modify ravel() result
   matrix before: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
   ravel() after change: [100   2   3   4   5   6   7   8   9  10  11  12]
   matrix after ravel() change:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
   Observation: original mat

Q4. A simple cognitive-assistive system wants to predict a user's assistance score based on three factors:
• Sleep hours
• Activity level
• Stress level
Consider: X = np.array([ [6, 70, 3], [5, 50, 6], [8, 80, 2], [4, 30, 8] ])  y = np.array([40, 65, 30, 85]) Here, each row represents one user and each column represents a feature. Perform the following:
a. Display the shape and dimensions of X.
b. Calculate: X.T and explain what the transpose represents.
c. Calculate the matrix product: X.T @ X
d. Calculate the matrix inverse using: np.linalg.inv() where appropriate.
e. Implement the Ordinary Least Squares equation: β = (XᵀX)⁻¹ Xᵀ y using NumPy.
f. Explain what the resulting coefficients represent in the context of the three user features.
g. A new user has: new_user = np.array([5, 40, 7]) Use your calculated coefficients to obtain a predicted assistance score.


In [4]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
], dtype=float)
y = np.array([40, 65, 30, 85], dtype=float)

print("X:")
print(X)
print("y:", y)

print("a. Shape of X:", X.shape)
print("   Dimensions (ndim) of X:", X.ndim)

print("b. X.T:")
print(X.T)
print("   Transpose represents the same data with rows and columns swapped.")
print("   Original X is 4 users x 3 features. X.T is 3 features x 4 users.")

XtX = X.T @ X
print("c. X.T @ X:")
print(XtX)

XtX_inv = np.linalg.inv(XtX)
print("d. Inverse of X.T @ X:")
print(XtX_inv)
print("   Check (X.T @ X) @ inverse is close to identity:")
print(np.round(XtX @ XtX_inv, 8))

beta = XtX_inv @ X.T @ y
print("e. OLS coefficients beta = (X.T @ X)^-1 @ X.T @ y:")
print(beta)

print(
    "f. The three coefficients correspond to Sleep hours, Activity level, and Stress level. "
    "Each value shows how much the predicted assistance score changes when that feature "
    "increases by 1 unit, holding the other features constant."
)
print("   Sleep hours coefficient:", beta[0])
print("   Activity level coefficient:", beta[1])
print("   Stress level coefficient:", beta[2])

new_user = np.array([5, 40, 7], dtype=float)
predicted = new_user @ beta
print("g. new_user:", new_user)
print("   Predicted assistance score:", predicted)


X:
[[ 6. 70.  3.]
 [ 5. 50.  6.]
 [ 8. 80.  2.]
 [ 4. 30.  8.]]
y: [40. 65. 30. 85.]
a. Shape of X: (4, 3)
   Dimensions (ndim) of X: 2
b. X.T:
[[ 6.  5.  8.  4.]
 [70. 50. 80. 30.]
 [ 3.  6.  2.  8.]]
   Transpose represents the same data with rows and columns swapped.
   Original X is 4 users x 3 features. X.T is 3 features x 4 users.
c. X.T @ X:
[[  141.  1430.    96.]
 [ 1430. 14700.   910.]
 [   96.   910.   113.]]
d. Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
   Check (X.T @ X) @ inverse is close to identity:
[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [-0.  0.  1.]]
e. OLS coefficients beta = (X.T @ X)^-1 @ X.T @ y:
[-0.15921454  0.14083853 10.06302242]
f. The three coefficients correspond to Sleep hours, Activity level, and Stress level. Each value shows how much the predicted assistance score changes when that feature increases by 1 unit, holding the other features constant.
   Sleep hours coeffi