Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

print("a) Addition of 2:", arr + 2)
print("b) Multiply by 3:", arr * 3)
print("c) Divide by 2:", arr / 2)


Original array: [1 2 3 4 5]
a) Addition of 2: [3 4 5 6 7]
b) Multiply by 3: [ 3  6  9 12 15]
c) Divide by 2: [0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])


In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("Original array:", arr)
print("a) Reversed array:", arr[::-1])


Original array: [1 2 3 6 4 5]
a) Reversed array: [5 4 6 3 2 1]


In [3]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
vals, counts = np.unique(x, return_counts=True)
most_freq = vals[np.argmax(counts)]
indices = np.where(x == most_freq)[0]

print("i. Array x:", x)
print("Most frequent value:", most_freq)
print("Indices:", indices)


i. Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value: 1
Indices: [0 5 7 8 9]


In [4]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
vals, counts = np.unique(y, return_counts=True)
max_count = counts.max()
most_freq_vals = vals[counts == max_count]

print("ii. Array y:", y)
print("Value counts:", dict(zip(vals.tolist(), counts.tolist())))
print("Most frequent value(s):", most_freq_vals, "(count =", max_count, ")")
for v in most_freq_vals:
    print("Indices of", v, ":", np.where(y == v)[0])


ii. Array y: [1 1 1 2 3 4 2 4 3 3]
Value counts: {1: 3, 2: 2, 3: 3, 4: 2}
Most frequent value(s): [1 3] (count = 3)
Indices of 1 : [0 1 2]
Indices of 3 : [4 8 9]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column


In [5]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("2-D Array:")
print(arr)

print("a) 1st row, 2nd column:", arr[0, 1])
print("b) 3rd row, 1st column:", arr[2, 0])


2-D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
a) 1st row, 2nd column: 20
b) 3rd row, 1st column: 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?


In [6]:
nikunj = np.linspace(10, 100, 25)
print("Array nikunj:")
print(nikunj)

print("\nDimensions (ndim):", nikunj.ndim)
print("Shape:", nikunj.shape)
print("Total elements (size):", nikunj.size)
print("Data type:", nikunj.dtype)
print("Total bytes (nbytes):", nikunj.nbytes)

print("\nTranspose using reshape(25, 1):")
print(nikunj.reshape(25, 1))

print("\nUsing .T attribute:")
print(nikunj.T)
print("Shape of .T:", nikunj.T.shape)

print(
    "\nNote: For a 1-D array, .T does not change the shape. "
    "To get a column vector, use reshape(25, 1) or nikunj[:, np.newaxis]."
)


Array nikunj:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type: float64
Total bytes (nbytes): 200

Transpose using reshape(25, 1):
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Using .T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape of .T: (25,)

Note: For a 1-D array, .T does not change the shape. To get a column vector, use reshape(25, 1) or nikunj[:, np.newaxis].


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.


In [7]:
ucs420_nikunj = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])
print("ucs420_nikunj:")
print(ucs420_nikunj)

print("\nMean:", np.mean(ucs420_nikunj))
print("Median:", np.median(ucs420_nikunj))
print("Max:", np.max(ucs420_nikunj))
print("Min:", np.min(ucs420_nikunj))
print("Unique elements:", np.unique(ucs420_nikunj))

reshaped_ucs420_nikunj = ucs420_nikunj.reshape(4, 3)
print("\nreshaped_ucs420_nikunj (4x3):")
print(reshaped_ucs420_nikunj)

resized_ucs420_nikunj = np.resize(ucs420_nikunj, (2, 3))
print("\nresized_ucs420_nikunj (2x3):")
print(resized_ucs420_nikunj)


ucs420_nikunj:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

reshaped_ucs420_nikunj (4x3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

resized_ucs420_nikunj (2x3):
[[10 20 30]
 [40 50 60]]
