UCS420: Cognitive Computing — Task-8 Sept (Self-Assessment)
Hypothesis Generation, Evaluation and Testing using Pandas and NumPy

Use only pandas and numpy (libraries from previous assignments). Do not use a for loop where vectorization or Boolean indexing can be used.


Q1. Create a minimal student-performance database with exactly 12 records and the columns: student_id, sleep_hours, study_hours, stress_level, extra_class, exam_score.
a. Build a pandas DataFrame with these 12 rows and print it.
b. Save the DataFrame to a CSV file named 1024160098_task-8_sept_data.csv and reload it.
c. Print the shape, column names, and dtypes of the database.
d. Using DataFrame loc, display rows 0, 3, 7 and 11.


In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

data = {
    "student_id": ["S01", "S02", "S03", "S04", "S05", "S06", "S07", "S08", "S09", "S10", "S11", "S12"],
    "sleep_hours": [7, 6, 8, 5, 7, 4, 8, 6, 7, 5, 8, 6],
    "study_hours": [4, 6, 3, 8, 5, 7, 2, 9, 4, 6, 5, 8],
    "stress_level": [3, 5, 2, 6, 4, 8, 3, 5, 4, 7, 2, 5],
    "extra_class": ["No", "Yes", "No", "Yes", "No", "Yes", "No", "Yes", "No", "Yes", "No", "Yes"],
    "exam_score": [62, 74, 58, 81, 68, 72, 54, 88, 64, 76, 70, 84]
}

df = pd.DataFrame(data)
print("a. Minimal student-performance database:")
print(df)

csv_name = "1024160098_task-8_sept_data.csv"
df.to_csv(csv_name, index=False)
df = pd.read_csv(csv_name)
print("\nb. Reloaded from", csv_name)
print(df)

print("\nc. Shape:", df.shape)
print("Column names:", list(df.columns))
print("Data types:")
print(df.dtypes)

print("\nd. Rows 0, 3, 7 and 11 using loc:")
print(df.loc[[0, 3, 7, 11]])


a. Minimal student-performance database:
   student_id  sleep_hours  study_hours  stress_level extra_class  exam_score
0         S01            7            4             3          No          62
1         S02            6            6             5         Yes          74
2         S03            8            3             2          No          58
3         S04            5            8             6         Yes          81
4         S05            7            5             4          No          68
5         S06            4            7             8         Yes          72
6         S07            8            2             3          No          54
7         S08            6            9             5         Yes          88
8         S09            7            4             4          No          64
9         S10            5            6             7         Yes          76
10        S11            8            5             2          No          70
11        S12          

Q2. Questions on pandas operations from the database created in Q1:
a. Select only the numeric columns and print their mean, median, max and min.
b. Filter and print all students who scored more than 70.
c. Group the data by extra_class and print the mean exam_score for each group.
d. Add a new column named score_category using a vectorized numpy condition: "High" if exam_score >= 75 else "Regular". Print the updated DataFrame.


In [2]:
numeric_cols = ["sleep_hours", "study_hours", "stress_level", "exam_score"]
print("a. Numeric summary:")
print("Mean:")
print(df[numeric_cols].mean())
print("\nMedian:")
print(df[numeric_cols].median())
print("\nMax:")
print(df[numeric_cols].max())
print("\nMin:")
print(df[numeric_cols].min())

print("\nb. Students with exam_score > 70:")
print(df[df["exam_score"] > 70])

print("\nc. Mean exam_score by extra_class:")
print(df.groupby("extra_class")["exam_score"].mean())

df["score_category"] = np.where(df["exam_score"] >= 75, "High", "Regular")
print("\nd. DataFrame with score_category:")
print(df)


a. Numeric summary:
Mean:
sleep_hours      6.416667
study_hours      5.583333
stress_level     4.500000
exam_score      70.916667
dtype: float64

Median:
sleep_hours      6.5
study_hours      5.5
stress_level     4.5
exam_score      71.0
dtype: float64

Max:
sleep_hours      8
study_hours      9
stress_level     8
exam_score      88
dtype: int64

Min:
sleep_hours      4
study_hours      2
stress_level     2
exam_score      54
dtype: int64

b. Students with exam_score > 70:
   student_id  sleep_hours  study_hours  stress_level extra_class  exam_score
1         S02            6            6             5         Yes          74
3         S04            5            8             6         Yes          81
5         S06            4            7             8         Yes          72
7         S08            6            9             5         Yes          88
9         S10            5            6             7         Yes          76
11        S12            6            8             5 

Q3. Convert the database into NumPy arrays and apply NumPy-II operations:
a. Create a 2-D NumPy array named ucs420_nikunj using sleep_hours, study_hours, stress_level and exam_score (12 rows, 4 columns). Print its ndim, shape, size, dtype and nbytes.
b. Using vectorization, add 1 extra study hour to the study_hours column of ucs420_nikunj and print the updated study hours.
c. Identify all exam scores greater than 70 using Boolean indexing and count how many exceed 70.
d. Reshape ucs420_nikunj to 4 rows and 12 columns as reshaped_ucs420_nikunj. Then resize it to 3 rows and 4 columns as resized_ucs420_nikunj. Print both.
e. Compute the transpose of the original 12x4 array using .T and also using reshape(). Can we do the same with the T attribute for a 1-D slice of exam scores?


In [3]:
ucs420_nikunj = df[["sleep_hours", "study_hours", "stress_level", "exam_score"]].to_numpy(dtype=float)
print("a. ucs420_nikunj:")
print(ucs420_nikunj)
print("ndim:", ucs420_nikunj.ndim)
print("shape:", ucs420_nikunj.shape)
print("size:", ucs420_nikunj.size)
print("dtype:", ucs420_nikunj.dtype)
print("nbytes:", ucs420_nikunj.nbytes)

updated_study = ucs420_nikunj[:, 1] + 1
print("\nb. Study hours after adding 1 hour:", updated_study)

exam_scores = ucs420_nikunj[:, 3]
greater_than_70 = exam_scores[exam_scores > 70]
print("\nc. Exam scores > 70:", greater_than_70)
print("Count exceeding 70:", np.sum(exam_scores > 70))

reshaped_ucs420_nikunj = ucs420_nikunj.reshape(4, 12)
resized_ucs420_nikunj = np.resize(ucs420_nikunj, (3, 4))
print("\nd. reshaped_ucs420_nikunj (4x12):")
print(reshaped_ucs420_nikunj)
print("resized_ucs420_nikunj (3x4):")
print(resized_ucs420_nikunj)

print("\ne. Transpose using .T:")
print(ucs420_nikunj.T)
print("Transpose using reshape(4, 12):")
print(ucs420_nikunj.reshape(4, 12))
score_slice = exam_scores.copy()
print("1-D exam score slice shape:", score_slice.shape)
print("Using .T on the 1-D slice:", score_slice.T, "shape:", score_slice.T.shape)
print("Using reshape to make a column vector:")
print(score_slice.reshape(12, 1))
print("Note: For a 1-D array, .T does not change the shape. Use reshape(n, 1) to get a column vector.")


a. ucs420_nikunj:
[[ 7.  4.  3. 62.]
 [ 6.  6.  5. 74.]
 [ 8.  3.  2. 58.]
 [ 5.  8.  6. 81.]
 [ 7.  5.  4. 68.]
 [ 4.  7.  8. 72.]
 [ 8.  2.  3. 54.]
 [ 6.  9.  5. 88.]
 [ 7.  4.  4. 64.]
 [ 5.  6.  7. 76.]
 [ 8.  5.  2. 70.]
 [ 6.  8.  5. 84.]]
ndim: 2
shape: (12, 4)
size: 48
dtype: float64
nbytes: 384

b. Study hours after adding 1 hour: [ 5.  7.  4.  9.  6.  8.  3. 10.  5.  7.  6.  9.]

c. Exam scores > 70: [74. 81. 72. 88. 76. 84.]
Count exceeding 70: 6

d. reshaped_ucs420_nikunj (4x12):
[[ 7.  4.  3. 62.  6.  6.  5. 74.  8.  3.  2. 58.]
 [ 5.  8.  6. 81.  7.  5.  4. 68.  4.  7.  8. 72.]
 [ 8.  2.  3. 54.  6.  9.  5. 88.  7.  4.  4. 64.]
 [ 5.  6.  7. 76.  8.  5.  2. 70.  6.  8.  5. 84.]]
resized_ucs420_nikunj (3x4):
[[ 7.  4.  3. 62.]
 [ 6.  6.  5. 74.]
 [ 8.  3.  2. 58.]]

e. Transpose using .T:
[[ 7.  6.  8.  5.  7.  4.  8.  6.  7.  5.  8.  6.]
 [ 4.  6.  3.  8.  5.  7.  2.  9.  4.  6.  5.  8.]
 [ 3.  5.  2.  6.  4.  8.  3.  5.  4.  7.  2.  5.]
 [62. 74. 58. 81. 68. 72. 54. 88.

Q4. Hypothesis generation should be written before looking at test results. For this student-performance problem, generate and test the following:
a. State one research problem for this database.
b. Write H0 and H1 for: students who attended extra classes have a higher mean exam score than students who did not.
c. This is a small sample (n < 30). Compute a two-sample t-statistic using numpy only:
   t = (mean_yes - mean_no) / sqrt(s_yes^2 / n_yes + s_no^2 / n_no)
d. Use significance level alpha = 0.05. For a one-tailed test with small samples, compare |t| with ttab = 1.812 (df ≈ 10). Make a decision: reject or do not reject H0.
e. Explain Type I and Type II error in the context of this extra-class hypothesis.


In [4]:
print("a. Research problem: Do extra classes improve exam scores of students?")

print("b. H0: Extra-class students do not have a higher mean exam score than other students.")
print("   H0: mu_yes <= mu_no")
print("   H1: Extra-class students have a higher mean exam score than other students.")
print("   H1: mu_yes > mu_no")

yes_scores = df.loc[df["extra_class"] == "Yes", "exam_score"].to_numpy(dtype=float)
no_scores = df.loc[df["extra_class"] == "No", "exam_score"].to_numpy(dtype=float)

mean_yes = np.mean(yes_scores)
mean_no = np.mean(no_scores)
s_yes = np.std(yes_scores, ddof=1)
s_no = np.std(no_scores, ddof=1)
n_yes = yes_scores.size
n_no = no_scores.size

t_cal = (mean_yes - mean_no) / np.sqrt((s_yes ** 2) / n_yes + (s_no ** 2) / n_no)
alpha = 0.05
t_tab = 1.812

print("c. Extra class = Yes scores:", yes_scores)
print("   Extra class = No scores:", no_scores)
print("   mean_yes =", mean_yes, "mean_no =", mean_no)
print("   s_yes =", s_yes, "s_no =", s_no)
print("   n_yes =", n_yes, "n_no =", n_no)
print("   t_cal =", t_cal)

print("d. alpha =", alpha)
print("   t_tab (one-tailed, df ~ 10) =", t_tab)
print("   t_cal > t_tab:", t_cal > t_tab)
if t_cal > t_tab:
    print("   Decision: Reject H0. The sample supports that extra classes are associated with a higher mean exam score.")
else:
    print("   Decision: Do not reject H0. There is not enough evidence that extra classes increase mean exam score.")

print(
    "e. Type I error (alpha): concluding that extra classes improve scores when they actually do not "
    "(rejecting a true H0). Type II error (beta): concluding that extra classes do not help when they actually do "
    "(failing to reject a false H0)."
)


a. Research problem: Do extra classes improve exam scores of students?
b. H0: Extra-class students do not have a higher mean exam score than other students.
   H0: mu_yes <= mu_no
   H1: Extra-class students have a higher mean exam score than other students.
   H1: mu_yes > mu_no
c. Extra class = Yes scores: [74. 81. 72. 88. 76. 84.]
   Extra class = No scores: [62. 58. 68. 54. 64. 70.]
   mean_yes = 79.16666666666667 mean_no = 62.666666666666664
   s_yes = 6.210206652492867 s_no = 6.022181221672648
   n_yes = 6 n_no = 6
   t_cal = 4.672098864011788
d. alpha = 0.05
   t_tab (one-tailed, df ~ 10) = 1.812
   t_cal > t_tab: True
   Decision: Reject H0. The sample supports that extra classes are associated with a higher mean exam score.
e. Type I error (alpha): concluding that extra classes improve scores when they actually do not (rejecting a true H0). Type II error (beta): concluding that extra classes do not help when they actually do (failing to reject a false H0).


Q5. A simple cognitive-assistive system wants to predict exam_score from three features: sleep_hours, study_hours and stress_level.
X contains these three columns from the database. y is exam_score.
a. Display the shape and dimensions of X.
b. Calculate X.T and explain what the transpose represents.
c. Calculate the matrix product X.T @ X.
d. Calculate the matrix inverse of X.T @ X using np.linalg.inv().
e. Implement the Ordinary Least Squares equation: beta = (X.T @ X)^-1 @ X.T @ y
f. Explain what the resulting coefficients represent for the three features.
g. A new student has: new_student = np.array([6, 7, 4]). Use the coefficients to obtain a predicted exam score.


In [5]:
X = df[["sleep_hours", "study_hours", "stress_level"]].to_numpy(dtype=float)
y = df["exam_score"].to_numpy(dtype=float)

print("X:")
print(X)
print("y:", y)

print("a. Shape of X:", X.shape)
print("   Dimensions (ndim) of X:", X.ndim)

print("b. X.T:")
print(X.T)
print("   Transpose swaps rows and columns. X is 12 students x 3 features. X.T is 3 features x 12 students.")

XtX = X.T @ X
print("c. X.T @ X:")
print(XtX)

XtX_inv = np.linalg.inv(XtX)
print("d. Inverse of X.T @ X:")
print(XtX_inv)

beta = XtX_inv @ X.T @ y
print("e. OLS coefficients beta:")
print(beta)

print(
    "f. The three coefficients correspond to sleep_hours, study_hours and stress_level. "
    "Each value shows how much the predicted exam score changes when that feature increases by 1 unit, "
    "holding the other features constant."
)
print("   sleep_hours coefficient:", beta[0])
print("   study_hours coefficient:", beta[1])
print("   stress_level coefficient:", beta[2])

new_student = np.array([6, 7, 4], dtype=float)
predicted = new_student @ beta
print("g. new_student:", new_student)
print("   Predicted exam score:", predicted)


X:
[[7. 4. 3.]
 [6. 6. 5.]
 [8. 3. 2.]
 [5. 8. 6.]
 [7. 5. 4.]
 [4. 7. 8.]
 [8. 2. 3.]
 [6. 9. 5.]
 [7. 4. 4.]
 [5. 6. 7.]
 [8. 5. 2.]
 [6. 8. 5.]]
y: [62. 74. 58. 81. 68. 72. 54. 88. 64. 76. 70. 84.]
a. Shape of X: (12, 3)
   Dimensions (ndim) of X: 2
b. X.T:
[[7. 6. 8. 5. 7. 4. 8. 6. 7. 5. 8. 6.]
 [4. 6. 3. 8. 5. 7. 2. 9. 4. 6. 5. 8.]
 [3. 5. 2. 6. 4. 8. 3. 5. 4. 7. 2. 5.]]
   Transpose swaps rows and columns. X is 12 students x 3 features. X.T is 3 features x 12 students.
c. X.T @ X:
[[513. 407. 320.]
 [407. 425. 331.]
 [320. 331. 282.]]
d. Inverse of X.T @ X:
[[ 0.00813927 -0.00700409 -0.00101494]
 [-0.00700409  0.03343514 -0.0312969 ]
 [-0.00101494 -0.0312969   0.04143281]]
e. OLS coefficients beta:
[4.67138853 5.53479696 2.23098537]
f. The three coefficients correspond to sleep_hours, study_hours and stress_level. Each value shows how much the predicted exam score changes when that feature increases by 1 unit, holding the other features constant.
   sleep_hours coefficient: 4.671